
["Ubuntu"]
color = "E95420"
name = "Ubuntu"
description = "Ubuntu support"

["Debian"]
color = "A81D33"
name = "Debian"
description = "Debian support"

["Linux-Mint"]
color = "87CF3E"
name = "Linux-Mint"
description = "Mint support"

["ElementaryOS"]
color = "64BAFF"
name = "ElementaryOS"
description = "ElementaryOS support"

["Shell"]
color = "E95420"
name = "Shell"
description = "Shell support"

["Actions"]
color = "181717"
name = "Actions"
description = "Actions support"

["Stats"]
color = "181717"
name = "Stats"
description = "Stats"

["Area: APT"]
color = "fcc7f0"
name = "Area: APT"
description = "APT/Repo related issues and PRs"

["Area: Snaps"]
color = "fcc7f0"
name = "Area: Snaps"
description = "Snaps related issues and PRs"

["Area: PIP"]
color = "fcc7f0"
name = "Area: PIP"
description = "PIP related issues and PRs"

["Area: Config"]
color = "fcc7f0"
name = "Area: Config"
description = "Config Issue"


["Actor: Dependabot"]
color = "025E8C"
name = "Actor: Dependabot"
description = "Action by Dependabot"

["Priority: Critical"]
color = "FF0000"
name = "Priority: Critical"
description = "Urgent/Extremely important"

["Priority: High"]
color = "FFA500"
name = "Priority: High"
description = "High importance"

["Priority: Low"]
color = "85e595"
name = "Priority: Low"
description = "Low prioirty tasks"

["Priority: Medium"]
color = "fbca04"
name = "Priority: Medium"
description = "Medium priority PR/issues"

["Status: Awaiting-Response"]
color = "00b1ed"
name = "Status: Awaiting-Response"
description = ""

["Status: Keep-Open"]
color = "00b1ed"
name = "Status: Keep-Open"
description = ""

["Status: Abandoned"]
color = "000000"
name = "Status: Abandoned"
description = "Issue/feature has been abandoned."

["Status: Done"]
color = "00FF9F"
name = "Status: Done"
description = "Completed and closed tasks/pr/issues"

["Status: In-Progress"]
color = "FFD649"
name = "Status: In-Progress"
description = "PR/Bug-fix WIP"

["Status: Invalid"]
color = "cccccc"
name = "Status: Invalid"
description = "Invalid"

["Status: Pending"]
color = "fef2c0"
name = "Status: Pending"
description = "Pending Tests and some more work"

["Status: Resolved"]
color = "00D100"
name = "Status: Resolved"
description = "Issue/PR has been resolved"

["Status: Stale"]
color = "c2c2c2"
name = "Status: Stale"
description = ""

["Status: Wont-Fix"]
color = "AFAFED"
name = "Status: Wont-Fix"
description = "Works as intended/beyond scope"

["Type: Bug"]
color = "e11d21"
name = "Type: Bug"
description = "Issue is a bug, Add Type: BugFix for PR"

["Type: Documentation"]
color = "fca6da"
name = "Type: Documentation"
description = "Docs"

["Type: Duplicate"]
color = "C8A2C8"
name = "Type: Duplicate"
description = "Issue or PR is duplicate"

["Type: Enhancement"]
color = "84b6eb"
name = "Type: Enhancement"
description = "Improve existing feature"

["Type: Feature"]
color = "7eed76"
name = "Type: Feature"
description = "Feature request/new feature"

["Type: Maintenance"]
color = "f4aea1"
name = "Type: Maintenance"
description = "Maintenance tasks/package updates/prettify etc"

["Type: Question"]
color = "cc317c"
name = "Type: Question"
description = "Questions"

["Type: Security"]
color = "f75d68"
name = "Type: Security"
description = "Security fixes"

["Dependencies"]
color = "0366d6"
name = "Dependencies"
description = ""

["Docker"]
color = "21ceff"
name = "Docker"
description = ""

["Go"]
color = "00ADD8"
name = "Go"
description = ""

["Python"]
color = "3776AB"
name = "Python"
description = "Python Deps"

["Rust"]
color = "ceef86"
name = "Rust"
description = ""

["Submodule"]
color = "F05032"
name = "Submodule"
description = ""

["Matlab"]
color = "0076A8"
name = "Matlab"
description = "Matlab"

["Terraform"]
color = "623CE4"
name = "Terraform"
description = "Terraform"

["Helm"]
color = "277A9F"
name = "Helm"
description = "Helm"

["Kubernetes"]
color = "326CE5"
name = "Kubernetes"
description = "Kubernetes"

["Ansible"]
color = "EE0000"
name = "Ansible"
description = "Ansible"

["Status: Locked"]
color = "4e5154"
name = "Status: Locked"
description = "Issue is locked"
