version: ~> 1.0
os:
- linux
language: python
dist: bionic
env:
  global:
  - DEBUG="TRAVIS"
  - AUTOPILOT="true"
python:
- "3.6"
services:
- docker
branches:
  except:
  - gh-pages
before_install:
- chmod +x ./after-effects
- chmod +x ./tests/*.sh
- chmod  +x ./build/*.sh
before_deploy:
- source ./build/export-travis-tag-message.sh
- ./build/set-git-config.sh
jobs:
  allow_failures:
  - env: TEST_ENV="Focal-Docker-ARM64"
  - env: TEST_ENV="Debian11-Docker"

  include:
  - stage: Shellcheck
    env: TEST_ENV="Shellcheck"
    script:
    - ./tests/test-shell-scripts.sh
    - ./tests/lint-dockerfiles.sh

  - stage: Test
    env: TEST_ENV="Focal-Docker"
    script: ./tests/test-distro.sh "ubuntu" "focal" "default.yml" "true"

  - env:
    - TEST_ENV="Focal-Docker-ARM64"
    - TRAVIS_ARCH="arm64"
    script: ./tests/test-distro.sh "ubuntu" "focal" "arm.yml" "true"
    arch: arm64

  - env: TEST_ENV="Debian10-Docker"
    script: ./tests/test-distro.sh "debian" "buster"

  - stage: Pre-Release-Builds
    env: TEST_ENV="Debian11-Docker"
    script: ./tests/test-distro.sh "debian" "bullseye" "pre-release.yml" "true"
notifications:
  email: false
