version: "2.4"
services:
  site:
    image: tprasadtp/mkdocs-material
    # userns_mode: host
    volumes:
      - ./docs:/home/user/app/docs:ro
      - ./mkdocs.yml:/home/user/app/mkdocs.yml:ro
    ports:
      - 127.0.0.1:8000:8000
