# Install Config
version: 1
name: Ubuntu
author: Cameron McQuinnn
# Configuration
config:
  # Enabled Tasks
  tasks:
    update: true
    upgrade: true
    # Add Repos
    # individual repos flags are mentioned under config.add_repo key
    repo: true
    # Add PPAs
    ppa: false
    # APT Packages
    apt: true
    # Whether to purge packages mentioned in config.purge key
    purge: false
    debs: true
    snaps: true
    gnome_shell_extensions: true
  # Repository Flags
  add_repo:
    skype: true
    google: true
    vscode: true
  # Flags
  flags:
  # Simulate flag will never be overridden by remote config.
    purge_enabled: true
    preserve_debs: true

  # Install components
  # APT Packages, Python Modules, Debian packages
  install:
    # Debian packages:  .deb files
    # CSV format similar to lists
    apt:
      # Admin related Stuff
      administration:
        - dconf-editor
        - gparted
      # Multimedia Tools. Photo Editors Converting tools, plex etc.
      multimedia:
        - audacity
        - vlc
        - gimp
      # Tools related to development.
      development:
        - curl
        - git
        - multistrap
        - build-essential
        - ruby-full
        - clang-format
        - bison
        - flex
        - openjdk-11-jdk-headless
        - openjdk-11-jre
        - pkg-config-arm-linux-gnueabihf
        - gcc-arm-linux-gnueabihf
        - pkg-config
	      - docker.io
        - shellcheck
        - python3-pip

      # Everything Else
      other:
        - u-boot-tools
        - qemu-user-static
        - plank
        - meld
        - chrome-gnome-shell
        - gnome-tweak-tool
        - kicad
        - kicad-libraries
        - gnome-shell-extension-prefs
        - neofetch

      # Packages supplied by external repositories & PPAs
      # Dont Mix packages provided by distribution and PPAs
      # Sometimes external repos and ppas fail, so better isolate it.
      external:
        - google-chrome-stable
        - code
    debian_packages:
      - https://zoom.us/client/latest/zoom_amd64.deb,zoom_amd64.deb
    snaps:
      classic:
        - slack
        - skype
  # GNOME Shell Extensions
  gnome_shell_extensions:
    # Extensions to install. Format: github-url,extension-UUID
    install:
      - https://github.com/dmo60/CoverflowAltTab.git,CoverflowAltTab@dmo60.de
      - https://github.com/kgshank/gse-sound-output-device-chooser.git,sound-output-device-chooser@kgshank.net
    # Extensions to disable. Format: extension-UUID
    disable:
      - ubuntu-dock@ubuntu.com
      - ubuntu-appindicators@ubuntu.com