# Version Config
api: 2
# Configuration
version:
  number: 560
  name: 5.6.0-Beta
  changelog: PPA Improvements, ROS2, 20.04
# Stats reporting
stats:
  report: false
  node: https://stats.ae.prasadt.com/report
