on:
  push:
    paths-ignore:
      - ".gitignore"
      - ".envrc"
      - "**.md"
      - ".vscode/**"
      - "README.md"
      - "CONTRIBUTING.md"
      - ".github/workflows/labels.yml"
      - ".github/labels.toml"
      - ".github/*.md"
      - "after-effects.asc"
    tags-ignore:
      - '**'
  pull_request:
name: build
env:
  DEBUG: ci
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          chmod +x after-effects
          chmod +x get-after-effects.sh
          chmod +x tests/*.sh
      - name: Shellcheck
        run: ./tests/test-shell-scripts.sh
  dockerlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Dockerfiles
        run: |
          ./tests/lint-dockerfiles.sh "docs"
  ubuntu:
    needs: [ "shellcheck", "dockerlint"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: [ "bionic", "eoan", "xenial", "host"]
    steps:
      - uses: actions/checkout@v2
      - name: Ubuntu ${{ matrix.release }}
        run: ./tests/test-distro.sh "ubuntu" "${{ matrix.release }}"
  debian:
    needs: [ "shellcheck", "dockerlint"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: [ "buster", "stretch"]
    steps:
      - uses: actions/checkout@v2
      - name: Debian ${{ matrix.release }}
        run: ./tests/test-distro.sh "debian" ${{ matrix.release }}
  ubuntu-upcoming:
    needs: [ "shellcheck", "dockerlint"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test on Ubuntu Upcoming
        run: ./tests/test-pre-release.sh "ubuntu" "focal"
  debian-upcoming:
    needs: [ "shellcheck", "dockerlint"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test on Debian Upcoming
        run: ./tests/test-pre-release.sh "debian" "bullseye" || true
  docs:
    needs: ["debian", "ubuntu"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Requirements
        run: pip install -r docs/requirements.txt
      - name: Build Docs
        run: |
          ./build/build-docs.sh
          ls ./ && ls ./_site/
          python3 build/version.py
          cat ./_site/commit.json
      - name: Clone gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: pages
      - name: Setup Git
        run: |
          echo "Setting git conf user.email"
          git config --global user.email "valarie-ci-bot@users.noreply.github.com" && echo "Done"
          echo "Setting git conf user.name"
          git config --global user.name "valarie-ci-bot" && echo "Done"
      - name: Copy _site folder to pages
        run: |
          rsync -avh --ignore-times --delete ./_site/ pages/
      - name: Commit changes
        run: |
          cd pages
          git add -A
          git commit -m "Pages Build for ${GITHUB_SHA:0:7}"
      - name: View Tree
        run: |
          sudo apt-get -qq update
          sudo apt-get install -qq -y tree
          cd pages
          tree -I '.git' ./
      - name: Push Pages
        run: |
          cd pages
          git checkout
          git push
        if: github.ref == 'refs/heads/master'
