on:
  push:
  pull_request:
name: build
env:
  DEBUG: ci
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          chmod +x after-effects
          chmod +x get-after-effects.sh
          chmod +x tests/*.sh
      - name: Shellcheck
        run: ./tests/test-shell-scripts.sh
  dockerlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Dockerfiles
        run: |
          ./tests/lint-dockerfiles.sh "docs"
  ubuntu:
    needs: [ "shellcheck", "dockerlint"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: [ "bionic", "eoan", "xenial", "host"]
    steps:
      - uses: actions/checkout@v2
      - name: Ubuntu ${{ matrix.release }}
        run: ./tests/test-distro.sh "ubuntu" "${{ matrix.release }}"
  debian:
    needs: [ "shellcheck", "dockerlint"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: [ "buster", "stretch"]
    steps:
      - uses: actions/checkout@v2
      - name: Debian ${{ matrix.release }}
        run: ./tests/test-distro.sh "debian" ${{ matrix.release }}
  ubuntu-upcoming:
    needs: [ "shellcheck", "dockerlint"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: est on Ubuntu Upcoming
        run: ./tests/test-pre-release.sh "ubuntu" "focal"
  debian-upcoming:
    needs: [ "shellcheck", "dockerlint"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test on Debian Upcoming
        run: ./tests/test-pre-release.sh "debian" "bullseye" || true
  docs:
    needs: ["debian", "ubuntu"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Git
        run: |
          echo "Setting git conf user.email"
          git config --global user.email "valarie-ci-bot@users.noreply.github.com" && echo "Done"
          echo "Setting git conf user.name"
          git config --global user.name "valarie-ci-bot" && echo "Done"
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Requirements
        run: pip install -r docs/requirements.txt
      - name: Build Docs
        run: |
          ./build/build-docs.sh
          ls ./ && ls ./_site/
          python3 build/version.py
          cat ./_site/commit.json
