on:
  push:
    paths-ignore:
      - ".gitignore"
      - ".envrc"
      - "**.md"
      - ".vscode/**"
      - ".dependabot/**"
      - "_config.yml"
      - "README.md"
    tags-ignore:
      - "*"
  pull_request:
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          chmod +x after-effects
          chmod +x get-after-effects.sh
          chmod +x tests/*.sh
      - name: Shellcheck
        run: ./tests/test-shell-scripts.sh
  ubuntu:
    needs: shellcheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [ "bionic", "eoan", "xenial", "host"]
    steps:
      - uses: actions/checkout@v2
      - name: Test on ${{ matrix.release }}
        run: ./tests/test-distro "ubuntu" "${{ matrix.release }}"
  debian:
    needs: shellcheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [ "buster", "stretch"]
    steps:
      - uses: actions/checkout@v2
      - name: Debian Test on ${{ matrix.release }}
        run: ./tests/test-distro "debian" ${{ matrix.release }}
