on:
  push:
  pull_request:
name: pre-release
jobs:
  prerelease:
    needs: shellcheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ["debian", "ubuntu"]
        include:
          - distro: "debian"
            release: bullsye
          - distro: "ubuntu"
            release: "focal"
    steps:
      - uses: actions/checkout@v2
      - run: shellcheck -e SC2154 -e SC2086 -e SC1117 after-effects
      - name: Test on Pre Release
        run: ./tests/test-distro.sh ${{ matrix.distro }} ${{ matrix.release }} "pre-release.yml" "true"
